SKILLS = {
    "python": ["python"],
    "java": ["java"],
    "javascript": ["javascript", "js", "typescript"],
    "node": ["node", "node.js"],
    "react": ["react", "react.js"],
    "react native": ["react native"],
    "rest api": ["rest api", "api"],
    "sql": ["sql", "mysql", "postgresql"],
    "html": ["html"],
    "css": ["css"],
    "git": ["git", "github"],
    "docker": ["docker"],
    "aws": ["aws"],
    "express": ["express", "express.js"],
    "wordpress": ["wordpress"],
    "django": ["django"],
    "flask": ["flask"],
    "mongodb": ["mongodb", "mongo"],
    "firebase": ["firebase"],
    "graphql": ["graphql"],
    "next.js": ["next.js", "nextjs"]
}